### PR TITLE
[WIP] Use node-tar instead of exec

### LINKED ISSUE #2: Move to some node-based tar system
Currently this library relies on the presence of the `tar` cli, which stinks for portability.

A PR that resolves this issue will
- [ ] add tests demonstrating how the current functionally works (my bad)
- [ ] replace shell'ed out tar with https://github.com/npm/node-tar (issuing any PRs to that repo we might need

### PR DESCRIPTION
**Pull request by jaswilli**
Closes #2
- Swap out cp.exec to system tar for node-tar module.
- Add body of test that checks content of tar file.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
@trek this looks like it should work?  Let me know if it still doesn't work and I'll take a look as I've used node-tar quite a few times, but at a glance this all looks pretty much perfect.

**Comment by trek** [comment]
Alas, a few things do not work:

- [ ] resulting unarchived directory does not match the name/structure of source directory (there is an additional layer of nesting and a randomly generated name, which makes further scripting of the tar difficult 
- [ ] tared files are symlinks and should be new files with the content of the source file

amd 2015-01-26 10-40-07

**Comment by trek** [comment]
Which is the same issue I ran into trying to use the simpler node-tar API. Then I tried to use the more manual API and only ended up with invalid tar archives, which proved difficult to debug.

**Comment by jaswilli** [comment]
> resulting unarchived directory does not match the name/structure of source directory (there is an additional layer of nesting and a randomly generated name, which makes further scripting of the tar difficult.

The archive itself contains an extra randomly generated directory name, or the archive is saved in a directory with a randomly generated name?  I'm not seeing the former, but the latter is the result of the `quick-temp` module.  I'm not sure if there's an option to change that behavior but if it's a deal-breaker I'm sure there's another solution to get the archive saved in a non-random location.

> tared files are symlinks and should be new files with the content of the source file.

So the desired behavior is to dereference symlinks?  That might require some acrobatics but I'll take a look and see what can be done...

**Comment by trek** [comment]
The current behavior is that if you start with
```bash
amd
├── dom-parser.js
├── dom-parser.js.map
├── event.js
├── event.js.map
├── index.js
├── index.js.map
├── status-codes.js
├── status-codes.js.map
├── unsafe-headers.js
└── unsafe-headers.js.map
```

then you end up with a tar that extracts to that same structure:

amd 2015-01-26 15-53-06

**Comment by trek** [comment]
Any luck?

**Comment by jaswilli** [comment]
I figured out a way to simulate the `-C` (change directory) behavior.  Still thinking about how (and where) the best way to dereference symlinks.  I wanted to write a transform stream to stick in between `fstream` and `node-tar` but they may be too tightly coupled.  Definitely need to read through both packages again and see if any strategies jump out at me though.

I pushed up another commit that demonstrates the "change directory" behavior, FWIW.

**Pull request closed without merging**
